#!/bin/zsh
if [ $(uname) = "Darwin" ]; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew install tig tree
  brew cask install iterm2
elif [ $(uname) = "Linux" ]; then
  sudo apt-get update
  sudo apt-get install build-essential
  sud apt-get install tree tig
else
  echo "Terminal not supported."
  exit 0
fi

./scripts/vim-setup
./scripts/tmux/setup
