#!/bin/zsh
if [ $(uname) = "Darwin" ]; then
  # Install Homebrew
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

  brew install tig tree
fi

./vim/setup
./tmux/setup
