#!/bin/bash

# Delete previous installation.
rm -rf ~/.vim/bundle/vimproc.vim
rm -rf ~/.vim/bundle/tsuquyomi
rm -rf ~/.vim/bundle/typescript-vim

mkdir -p ~/.vim/bundle

# Install and compile procvim.vim
git clone https://github.com/Shougo/vimproc.vim.git ~/.vim/bundle/vimproc.vim
pushd ~/.vim/bundle/vimproc.vim
make
popd

# Install tsuquyomi
git clone https://github.com/Quramy/tsuquyomi.git ~/.vim/bundle/tsuquyomi

# For syntax highlighting
git clone https://github.com/leafgarland/typescript-vim.git ~/.vim/bundle/typescript-vim
