#!/bin/bash
if [ ! $(uname) = "Darwin" ]; then
  sudo apt-get install git curl
fi

# Remove previous vim configuration.
if [ -d ~/.vim ]; then
  echo "Deleting old .vim directory."
  rm -rf ~/.vim
fi

if [ -f ~/.vimrc ]; then
  echo "Deleting old .vimrc."
  rm ~/.vimrc
fi

# Check if there is a copy of .vimrc on the current or parent directory
# and create a hard symlink to the home directory's .virmrc file if it exists.
if [ -f .vimrc ]; then
  ln -n .vimrc ~/.vimrc
elif [ -f ../.vimrc ]; then
  ln -n ../.vimrc ~/.vimrc
else
  echo "File .vimrc not found."
  exit 0
fi

# Install pathogen
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install CTRLP plugin.
# git clone https://github.com/ctrlpvim/ctrlp.vim.git ~/.vim/bundle/ctrlp.vim

# Download and install NERDTREE.
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree

# Install vim-colors-solarized
git clone https://github.com/altercation/vim-colors-solarized.git ~/.vim/bundle/vim-colors-solarized
