#!/bin/bash

# Terminate all EC2 instances first.
aws ec2 describe-instances | jq -r .Reservations[].Instances[].InstanceId | \
  while read -r instance ; do
    echo "Terminating $instance..."
    aws ec2 terminate-instances --instance-id $instance
  done

# Delete all subnets.
aws ec2 describe-subnets | jq -r '.Subnets[].SubnetId' | \
  while read -r subnet ; do
    echo "Deleting $subnet."
    aws ec2 delete-subnet --subnet-id $subnet
  done

# Delete the VPCs.
aws ec2 describe-vpcs --filters Name=isDefault,Values=false | jq -r .Vpcs[].VpcId | \
  while read -r vpc; do
    echo "Deleting $vpc..."
    aws ec2 delete-vpc --vpc-id $vpc
  done