#!/bin/bash
aws ec2 describe-security-groups | jq -r '.SecurityGroups[] | select(contains({GroupName: "default"}) | not) | .GroupId' | \
  while read -r sg ; do
    echo "Deleting $sg."
    aws ec2 delete-security-group --group-id $sg;
  done