#!/bin/bash

VPC_ID=$1
[ -z '$VPC' ] && exit

# Get the VPC's Internet Gateway then detach it.

IG_ID=$(aws ec2 describe-internet-gateways \
  --filter Name=attachment.vpc-id,Values=$VPC_ID \
  | jq -r .InternetGateways[].InternetGatewayId)

if [ ! -z '$IG_ID' ]; then
  echo "Detaching the VPC's($VPC_ID) Internet Gateway($IG_ID)..."
  RESULT=$(aws ec2 detach-internet-gateway --internet-gateway-id $IG_ID --vpc-id $VPC_ID)

  if [ ! -z '$RESULT' ]; then
    echo "Internet Gateway($IG_ID) detached successfully."
  else
    echo "Detaching the VPC's($VPC_ID) Internet Gateway($IG_ID) failed."
    exit
  fi
fi

aws ec2 describe-subnets --filter Name=vpc-id,Values=$VPC_ID | jq -r .Subnets[].SubnetId \
  | while read -r subnet ; do
    echo "Deleting $subnet."
    aws ec2 delete-subnet --subnet-id $subnet
  done

# Get the route to the internet via the VPC's Internet Gateway.

# RT_ID=$(aws ec2 describe-route-tables \
#  --filter Name=route.gateway-id,Values=$IG_ID \
#  | jq -r .RouteTables[].RouteTableId)

# aws ec2 delete-route --route-table-id $RT_ID --destination-cidr-block 0.0.0.0/0

echo 'Deleting the VPC($VPC_ID)...'
$RESULT=$(aws ec2 delete-vpc --vpc-id $VPC_ID)

if [ ! -z '$RESULT' ]; then
  echo "VPC($VPC_ID) deleted successfully."
else
  echo "Deleting the VPC($VPC_ID) failed."
  exit
fi
