#!/bin/bash
aws ec2 describe-instances | jq -r .Reservations[].Instances[].InstanceId | \
  while read -r instance ; do
    echo "Terminating $instance..."
    aws ec2 terminate-instances --instance-id $instance
  done
