#!/bin/bash
aws ec2 describe-instances | jq -r .Reservations[].Instances[].InstanceId | \
  while read -r instance ; do
    echo "Deleting $instance."
    aws ec2 terminate-instance --instance-id $instance
  done
