#!/bin/bash

# OSX doesn't read .bashrc.
if [ $(uname) = "Darwin" ]; then
  # Delete previous .bash_profile file if it already exists in the home directory.
  if [ -f ~/.bash_profile ]; then
    echo "Backing up previous .bash_profile file..."
    mv ~/.bash_profile ~/.bash_profile.bak
  fi

  # Create a hard symlink for .bash_profile file.
  if [ -f .bash_profile ]; then
    ln -n .bash_profile ~/.bash_profile
    echo "Copied .bash_profile file to home directory."
  elif [ -f ../.bash_profile ]; then
    ln -n ../.bash_profile ~/.bash_profile
    echo "Copied .bash_profile file to home directory."
  else
    echo "File .bash_profile not found."
  fi
elif [ $(uname) = "Linux" ]; then
  # Delete previous .bashrc file if it already exists in the home directory.
  if [ -f ~/.bashrc ]; then
    echo "Backing up previous .bashrc file..."
    mv ~/.bashrc ~/.bashrc.bak
  fi

  # Create a hard symlink for .bashrc file.
  if [ -f .bashrc ]; then
    ln -n .bashrc ~/.bashrc
    echo "Copied .bashrc file to home directory."
  elif [ -f ../.bashrc ]; then
    ln -n ../.bashrc ~/.bashrc
    echo "Copied .bashrc file to home directory."
  else
    echo "File .bashrc not found."
  fi
else
  echo "Not supported."
  exit 0
fi

# Delete previous .aliases file if it already exists in the home directory.
if [ -f ~/.aliases ]; then
  echo "Removing previous .aliases file..."
  rm -f ~/.aliases
fi

# Create a hard symlink for .aliases file.
if [ -f .aliases ]; then
  ln -n .aliases ~/.aliases
  echo "Copied .aliases file to home directory."
elif [ -f ../.aliases ]; then
  ln -n ../.aliases ~/.aliases
  echo "Copied .aliases file to home directory."
else
  echo "File .aliases not found."
fi

# Delete previous .env file if it already exists in the home directory.
if [ -f ~/.env ]; then
  echo "Removing previous .env file..."
  rm -f ~/.env
fi

# Create a hard symlink for .env file.
if [ -f .env ]; then
  ln -n .env ~/.env
  echo "Copied .env file to home directory."
elif [ -f ../.env ]; then
  ln -n ../.env ~/.env
  echo "Copied .env file to home directory."
else
  echo "File .env not found."
fi

