#!/bin/bash
BACKUP_DIR=~/dotfiles.bak/`date +"%m-%d-%y-%T"`
mkdir -p $BACKUP_DIR

if [ -f ~/.bash_profile ]; then
  echo "Backing up previous .bash_profile file..."
  mv ~/.bash_profile $BACKUP_DIR
fi

if [ -f .bash_profile ]; then
  ln -n .bash_profile ~/.bash_profile
  echo "Copied .bash_profile file to home directory."
elif [ -f ../.bash_profile ]; then
  ln -n ../.bash_profile ~/.bash_profile
  echo "Copied .bash_profile file to home directory."
else
  echo "File .bash_profile not found."
fi


if [ -f ~/.bashrc ]; then
  echo "Backing up previous .bashrc file..."
  mv ~/.bashrc $BACKUP_DIR
fi

if [ -f .bashrc ]; then
  ln -n .bashrc ~/.bashrc
  echo "Copied .bashrc file to home directory."
elif [ -f ../.bashrc ]; then
  ln -n ../.bashrc ~/.bashrc
  echo "Copied .bashrc file to home directory."
else
  echo "File .bashrc not found."
fi


if [ -f ~/.aliases ]; then
  echo "Backing up previous .aliases file..."
  mv ~/.aliases $BACKUP_DIR
fi

if [ -f .aliases ]; then
  ln -n .aliases ~/.aliases
  echo "Copied .aliases file to home directory."
elif [ -f ../.aliases ]; then
  ln -n ../.aliases ~/.aliases
  echo "Copied .aliases file to home directory."
else
  echo "File .aliases not found."
fi


if [ -f ~/.env ]; then
  echo "Backing up previous .env file..."
  mv ~/.env $BACKUP_DIR
fi

if [ -f .env ]; then
  ln -n .env ~/.env
  echo "Copied .env file to home directory."
elif [ -f ../.env ]; then
  ln -n ../.env ~/.env
  echo "Copied .env file to home directory."
else
  echo "File .env not found."
fi
