#!/bin/bash
BACKUP_DIR=~/dotfiles.bak/git/`date +"%m-%d-%y-%T"`
mkdir -p $BACKUP_DIR

if [ -f ~/.gitignore_global ]; then
  echo "Backing up previous .gitignore_global file..."
  mv ~/.gitignore_global $BACKUP_DIR
fi

if [ -f .gitignore_global ]; then
  ln -n .gitignore_global ~/.gitignore_global
  echo "Moved .gitignore_global file to $HOME."
elif [ -f ../.gitignore_global ]; then
  ln -n ../.gitignore_global ~/.gitignore_global
  echo "Moved .gitignore_global file to $HOME."
else
  echo "File .gitignore_global not found."
fi


if [ -f ~/.gitconfig ]; then
  echo "Backing up previous .gitconfig file..."
  mv ~/.gitconfig $BACKUP_DIR
fi

if [ -f .gitconfig ]; then
  ln -n .gitconfig ~/.gitconfig
  echo "Copied .gitconfig file to $HOME."
elif [ -f ../.gitconfig ]; then
  ln -n ../.gitconfig ~/.gitconfig
  echo "Copied .gitconfig file to $HOME."
else
  echo "File .gitconfig not found."
fi
