#!/bin/bash
if [ $(uname) = "Darwin" ]; then
  brew install zsh

  # Install powerline fonts.
  git clone https://github.com/powerline/fonts.git --depth=1
  cd fonts
  ./install.sh
  cd ..
  rm -rf fonts

elif [ $(uname) = "Linux" ]; then
  sudo apt-get install zsh curl fonts-powerline
else
  echo "Terminal not supported."
  exit 0
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

