#!/bin/bash
if [ $(uname) = "Darwin" ]; then
  brew install zsh

  # Install powerline fonts.
  git clone https://github.com/powerline/fonts.git --depth=1
  cd fonts
  ./install.sh
  cd ..
  rm -rf fonts

elif [ $(uname) = "Linux" ]; then
  sudo apt-get install zsh curl fonts-powerline
else
  echo "Terminal not supported."
  exit 0
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Delete previous .aliases file if it already exists in the home directory.
if [ -f ~/.aliases ]; then
  echo "Removing previous .aliases file..."
  rm -f ~/.aliases
fi

# Create a hard symlink for .aliases file.
if [ -f .aliases ]; then
  ln -n .aliases ~/.aliases
  echo "Copied .aliases file to home directory."
elif [ -f ../.aliases ]; then
  ln -n ../.aliases ~/.aliases
  echo "Copied .aliases file to home directory."
else
  echo "File .aliases not found."
fi

# Delete previous .env file if it already exists in the home directory.
if [ -f ~/.env ]; then
  echo "Removing previous .env file..."
  rm -f ~/.env
fi

# Create a hard symlink for .env file.
if [ -f .env ]; then
  ln -n .env ~/.env
  echo "Copied .env file to home directory."
elif [ -f ../.env ]; then
  ln -n ../.env ~/.env
  echo "Copied .env file to home directory."
else
  echo "File .env not found."
fi

# Delete previous .zshrc file if it already exists in the home directory.
if [ -f ~/.zshrc ]; then
  echo "Removing previous .zshrc file..."
  rm -f ~/.zshrc
fi

# Create a hard symlink for .zshrc file.
if [ -f .zshrc ]; then
  ln -n .zshrc ~/.zshrc
  echo "Copied .zshrc file to home directory."
elif [ -f ../.zshrc ]; then
  ln -n ../.zshrc ~/.zshrc
  echo "Copied .zshrc file to home directory."
else
  echo "File .zshrc not found."
fi
