#!/bin/bash
if [ $(uname) = "Darwin" ]; then
  brew install zsh
elif [ $(uname) = "Linux" ]; then
  sudo apt-get install zsh curl
else
  echo "Terminal not supported."
  exit 0
fi

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
