#!/bin/bash
if [ $(uname) = "Darwin" ]; then
  echo "Installing Homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew install tmux coreutils
  brew install grep --with-default-names
elif [ $(uname) = "Linux" ]; then
  sudo apt-get install build-essential curl tmux xclip
else
  echo "Terminal not supported."
  exit 0
fi

echo "Setting up dotfiles..."
DOTFILES_REPO=$HOME/.dotfiles
DOTFILES_OLD=$HOME/.dotfiles.old/`date +"%m-%d-%y-%T"`

[ -f $DOTFILES_REPO ] && rm -rf $DOTFILES_REPO
git clone --bare https://github.com/EmmanuelCorrales/dotfiles.git $DOTFILES_REPO

dotfiles() {
  git --git-dir=$DOTFILES_REPO --work-tree=$HOME $@
}

mkdir -p $DOTFILES_OLD
dotfiles checkout

if [ $? = 0 ]; then
  echo "Checked out dotfiles.";
else
  echo "Backing up pre-existing dot files.";
  dotfiles checkout 2>&1 | grep -P "\t+" | awk {'print $1'} | xargs -I {} mv $HOME/{} $DOTFILES_OLD/
fi;

dotfiles checkout
dotfiles config status.showUntrackedFiles no


# Vundle setup
git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
echo "Downloading and installing Vim plugins with Vundle..."
echo | echo | vim +PluginInstall +qall &>/dev/null
